namespace NinkyClicker.Input;

public struct HardwareInput
{
    /// <summary>
    /// Value specifying the message generated by the input hardware. 
    /// </summary>
    public UInt32 Msg;

    /// <summary>
    /// Specifies the low-order word of the lParam parameter for uMsg. 
    /// </summary>
    public UInt16 ParamL;

    /// <summary>
    /// Specifies the high-order word of the lParam parameter for uMsg. 
    /// </summary>
    public UInt16 ParamH;
}